version: 2
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - migrations
    - vendor
    - api

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - revive
    - gocyclo
    - ineffassign
    - gosec
    - depguard
    - bodyclose

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    ignoreGeneratedHeader: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have comment or be unexported"
    - "error return value .* not checked"